/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.ArrayList;

public class Restaurant implements Business{
    String name;
    Double avererageStars = 0.0;
    int priceCategory;
    ArrayList<Review> reviews = new ArrayList<>();
    public Restaurant(String name, int priceCategory ){
        this.name = name;
        this.priceCategory = priceCategory;
    }
    public void addReview(String body, String author, Double stars){
        Review review = new Review(body,author,stars);
        Double averageStars = this.avererageStars;
        this.reviews.add(review);
        if (averageStars == 0.0){
            this.avererageStars = stars;
        } else {
            this.avererageStars = (this.avererageStars + stars)/2;
        }
    }
    public String toString(){
        String res = this.name + " has " + this.avererageStars + " stars; It exists in price catagory: " + this.priceCategory;
        System.out.println(res);
        return res;
    }
}
