/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void test_roll() {
        Library classUnderTest = new Library();
        assertNotNull("The array should not be null", classUnderTest.roll(4));
        int[] rollArray = classUnderTest.roll(4);
        assertEquals("The array should have a length", 4,rollArray.length);
        assertNotEquals("The arrays values should not be zero",0,rollArray[0]);
    }
    //containsDuplicates
    @Test public void test_containsDuplicates() {
        Library classUnderTest = new Library();
        int[] noDupes = new int[]{1,2,4,33,564,46565};
        int[] dupes = new int[]{1, 3, 4,7,87,3,45};
        assertTrue("Returns true when array contains duplicates",classUnderTest.containsDuplicates(dupes) );
        assertFalse("Returns false when array does not contain duplicates",classUnderTest.containsDuplicates(noDupes) );
    }
    @Test public void test_averages(){
        Library classUnderTest = new Library();
        int[] input = new int[]{2, 2, 3, 3};
        assertEquals("Returns average",classUnderTest.averages(input),2.5,0);
    }
    @Test public void test_averagesArrays(){
        Library classUnderTest = new Library();
        int[][] testArrays ={
                {3,4,5},
                {2,3,4},
                {6,7,8}
        };
        int[] expected = new int[]{2,3,4};
        assertArrayEquals("Should return the array with the lowest average",classUnderTest.averagesArrays(testArrays),expected);
    }


}
