/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class RestaurantTest {
    @Test public void test_RestaurantConstructor(){
        String rr_name = new String("Le Duck");
        int priceCat = 3;
        Restaurant test = new Restaurant(rr_name,priceCat);
//        Restaurant test = new Restaurant(rr_name, avererageStars,priceCat );
        assertTrue("Name should be correct", test.name.equals("Le Duck"));
        assertEquals("price category should be correct", test.priceCategory, priceCat);

    }
    @Test public void test_res_toString(){
        String rr_name = new String("Le Duck");
        int priceCat = 3;
        Restaurant test = new Restaurant(rr_name,priceCat);
        Double stars = 5.0;
        test.addReview("asdf", "na e ", stars);
        assertTrue("To string should return the phrase", test.toString().equals("Le Duck has 5.0 stars; It exists in price catagory: 3"));
    }
    @Test public void test_review_tostring (){
        Review test = new Review("I hate everything", "Mr.P", 5.0);
        assertTrue("toString returns a correctly formatted string",test.toString().equals("Mr.P : 5.0 stars. I hate everything"));
    }
    @Test public void test_average_stars (){
        Restaurant dennys = new Restaurant("Dennys",1);
        dennys.addReview("Bad", "everybody", 5.0);
        dennys.addReview("Bad", "everybody", 0.0);
        assertEquals("Average stars calculated", dennys.avererageStars, 2.5, 0.00001);
    }
}
