/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public int[] roll(int numOfRolls){
        int[] res = new int [numOfRolls];
        for(int i = 0; i < numOfRolls; i++){
            res[i] = (int) Math.floor(Math.random()* 6 + 1);
        }
        return res;
    }
    public boolean containsDuplicates(int[] input){
        for (int i = 0; i < input.length;i++) {
            for (int j = 0; j <input.length; j++){
                if(input[i] ==input[j] && i != j){
                    return true;
                }
            }
        }
        return false;
    }
    public double average(int[] input){
        double res = 0;
        for(int i = 0; i < input.length; i++){
            res+= input[i];
        }
        res = res/input.length;
        return res;
    }
    public int[] averageArrays(int[][] input){
        double lowest = average(input[0]);
        int lowestIndex = 0;
        for (int i = 0; i <input.length; i++){
            double currentAverage = average(input[i]);
            if (average(input[i])<lowest){
                lowest = currentAverage;
                lowestIndex = i;
            }
        }
        return input[lowestIndex];
    }
}
